# Generated by Django 3.2 on 2021-05-23 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0004_campaign_uniqueauthorplusname'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='slug',
            field=models.SlugField(default='djangodbmodelsfieldsrelatedforeignkey/djangodbmodelsfieldscharfield', max_length=300),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='name',
            field=models.CharField(db_index=True, max_length=100),
        ),
    ]
