# Generated by Django 3.2 on 2021-05-23 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0009_alter_campaign_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaignimage',
            name='alt',
            field=models.CharField(default='Campaign image', max_length=100, verbose_name='tip'),
        ),
    ]
