# Generated by Django 3.2 on 2021-06-14 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0011_auto_20210524_1926'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campaign',
            name='youtube_url',
        ),
        migrations.AddField(
            model_name='campaign',
            name='youtube_id',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
