# Generated by Django 3.2 on 2021-06-20 15:34

from django.db import migrations
import martor.models


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0018_commentlike_uniqueauthorpluscomment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='description',
            field=martor.models.MartorField(),
        ),
    ]
