# Generated by Django 3.2 on 2021-06-23 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0019_alter_campaign_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='campaign',
            options={'ordering': ('expiration_date',)},
        ),
    ]
